### PR TITLE
fix: default field default with test

### LINKED ISSUE #7: [Bug]: default prop not adding field
### Version Target

v1.7.1

### What happened?

Defining default on prop not adding field with the value. Seems like the `Transform` of `class-transformer` not adding because the `plainToInstance` is running first before the `class-validator` assign the prop option on model class. Here is the example of model config
```typescript
export class Breed {
  @Prop({ required: true })
  @Key({ prefix: "breed_name::" })
  name: string

  @Prop({ required: false, default: "-" })
  remark: string
}
```

### Relevant log output

```shell
{"name": "Example"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by theycantrevealus**
Close #7 

`Transform` class seems like not executing while creating prop rather than on start. Alternate using `Reflector`
Or other method is directly using `class-transformer` on the schema

### CODE REVIEW

File: src/model.ts [hunk 1]
```diff
@@ -127,6 +127,19 @@ export class CouchBaseModel<T> {
...
+    for (const [key, defaultValue] of Object.entries(defaults)) {
+      if (
+        (instance as any)[key] === undefined ||
+        (instance as any)[key] === null
+      ) {
+        ;(instance as any)[key] =
+          typeof defaultValue === "function" ? defaultValue() : defaultValue
+      }
+    }
+
```
Comment (RifqiSah) [inline src/model.ts]: Perhaps it would be better to apply default first before `plainToInstance()`. Like this
```
applyDefaults(data)
const instance = plainToInstance(this.schemaClass, data)
const errors = await validate(instance)
```

Comment (RifqiSah) [reply src/model.ts]: Wait i'll add the fn directly, please check https://github.com/theycantrevealus/nestjs-couchbase/pull/8/commits/73cb216aabf131bb12d93481f06b214f0fce6efd mas
